set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
 Plugin 'gmarik/Vundle.vim'

 "Search for files
 Plugin 'kien/ctrlp.vim'

 "Tab line goodies
 Plugin 'bling/vim-airline'

 "GIT support
 Plugin 'tpope/vim-fugitive'
 
 Plugin 'pangloss/vim-javascript'

 Plugin 'FelikZ/ctrlp-py-matcher'

 "Show errors on lines
 Plugin 'scrooloose/syntastic'

 Plugin 'tpope/vim-unimpaired'

 "Support for jade color scheme
 Plugin 'digitaltoad/vim-jade.git'

 "Nerdtree show a tree structure to navigate files
  Plugin 'scrooloose/nerdtree'

 "Silver bullet search
 Plugin 'rking/ag.vim'

 Plugin 'tomtom/tcomment_vim'

 "Cmd+v support
 Plugin 'ConradIrwin/vim-bracketed-paste'
 
 "Show ident guides
  Plugin 'nathanaelkane/vim-indent-guides'

 "Vim plugin which shows a git diff in the gutter (sign column) and  stages/reverts hunks.
 Plugin 'airblade/vim-gitgutter'

 " Prefer local repo install of eslint over global install with syntastic
 Plugin 'mtscout6/syntastic-local-eslint.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on    " required

" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more detals or wiki for FAQ
" Put your non-Plugin stuff after this line




syntax on                         " show syntax highlighting
colorscheme molokai
filetype plugin indent on
set autoindent                    " set auto indent
set ts=4                          " set indent to 4 spaces
set shiftwidth=4
set expandtab                     " use spaces, not tab characters
set number                        " show absolute line numbers
set showmatch                     " show bracket matches
set ignorecase                    " ignore case in search
set hlsearch                      " highlight all search matches
set cursorline                    " highlight current line
set smartcase                     " pay attention to case when caps are used
set incsearch                     " show search results as I type
set ttimeoutlen=100               " decrease timeout for faster insert with 'O'
set vb                            " enable visual bell (disable audio bell)
set ruler                         " show row and column in footer
set scrolloff=2                   " minimum lines above/below cursor
set laststatus=2                  " always show status bar
set list listchars=tab:»·,trail:· " show extra space characters
set nofoldenable                  " disable code folding
set clipboard=unnamed             " use the system clipboard
set wildmenu                      " enable bash style tab completion
set wildmode=list:longest,full
set autoread                      " Reload the files open with vim and edited with others programs

"set the leader key
:let mapleader = "-"

" This are remaps for various things

"airline config
let g:airline_powerline_fonts = 1
let g:airline_theme='powerlineish'

"CtrlP configuration
"Change and ignore some files so ctrlP is faster!
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
      \ --ignore .git
      \ --ignore .svn
      \ --ignore .hg
      \ --ignore .DS_Store
      \ --ignore "**/*.pyc"
      \ -g ""'

"Change the ctrlP matcher this one is better than vim matcher
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }

" Setting backupdir outside the project
set backupdir=~/.vim/backup/
set directory=~/.vim/swap/
set undodir=~/.vim/undo/


"Syntastic configurations

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 2
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_javascript_checkers = ['eslint']

"NERDTree
map <C-w>t  :NERDTreeToggle<CR>

" ==== vim-indent-guides-config ====

let g:indent_guides_enable_on_vim_startup = 0
let g:indent_guides_exclude_filetypes = ['help', 'nerdtree']
let g:indent_guides_auto_colors = 1
let g:indent_guides_color_change_percent = 1
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=black  ctermbg=7
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=15
